### ISSUE TITLE
Setting up working directory?

### ISSUE THREAD

**Issue by fhoshino** [HikariKnight/hotkeyD#3]
Please implement a function to setup a working directory like "SetWorkingDir %A_Desktop%" in autohotkey, which could be specified in the ini config file.

**Comment by HikariKnight** [comment]
I will look into it, for now you can do it using cmd and the hide options, sadly this does not work properly with spaces, you could however also instead make the cmd run a batch script (it will still hide the cmd window)

not a perfect solution but a workaround for now until i get it implemented :)

```ini
[example1]
Modkeys=alt+win
Hotkey=e
Launch=cmd.exe
Args=/c "cd C:\customdir\ & %CD%\program.exe"
Hide=true

[example2]
Modkeys=alt+win
Hotkey=b
Launch=cmd.exe
Args=/c "C:\scripts\custom.bat"
Hide=true
```

custom.bat
```bat
@echo off
cd "C:\customdir\"
"%CD%\program.exe"
```

**Comment by HikariKnight** [comment]
@fhoshino hey this has now been implemented, enjoy :)

just use
```ini
Workdir="C:\path\to\a folder\"
```
