### ISSUE TITLE
Close active window & launch discord.

### ISSUE THREAD

**Issue by Sokoloft** [HikariKnight/hotkeyD#5]
Hello. 

I'd like to set alt+q to close my active window. Unsure how to do this. 
Also I cannot get discord to launch. I've tried many different combinations.

`
[discord]
Modkeys=alt
Hotkey=5
Launch=C:\Users\Sokoloft\AppData\Local\Discord\Update.exe --processStart Discord.exe
Workdir="C:\Users\Sokoloft\AppData\Local\Discord\app-1.0.9003"

[kill current-window]
Modkeys=alt
Hotkey=q
Launch=cmd.exe
Args=/c "winClose"
Hide=true
`

Thanks.

**Comment by HikariKnight** [comment]
this is not a function this project provides as it is aimed solely to be a hotkey application launcher that does not trigger anti cheat software.
so in this case you would have to create a script in something like autohotkey, autoit or your favorite scripting/programming language and create a program that closes the currently focused application and have hotkeyd launch that on a keypress.

Obviously if you have a game up and do the keypress to run a script made in autoit or autohotkey, the anti cheat software will most likely get triggered and kick you off the game.

I do not want to make hotkeyd start having the ability to send keypresses (alt+f4) to avoid angering the anti cheat systems in some games :)

**Comment by Sokoloft** [comment]
Alright. I'll try and make some sort of batch file that will close the active window. 

However I'm unsure what my issue is with discord. I cannot get it to launch with hotkeyD at all. 

Maybe I'll make a batch for that too. I'll figure something out.

Thanks.

**Comment by Sokoloft** [comment]
I found some code and put together a powershell script. It isn't the best, however I'm trying to make my bindings similar to how I have my linux systems setup.

```
[close-current-window]
Modkeys=alt
Hotkey=q
Launch=powershell.exe
Args=/c "C:\Users\Sokoloft\Documents\hotkeyd\scripts\close_aw.ps1"
Hide=true
```

```
[CmdletBinding()]            
Param(            
)            
Add-Type @"
  using System;
  using System.Runtime.InteropServices;
  public class UserWindows {
    [DllImport("user32.dll")]
    public static extern IntPtr GetForegroundWindow();
}
"@            
try {            
$ActiveHandle = [UserWindows]::GetForegroundWindow()           
$Process = Get-Process | ? {$_.MainWindowHandle -eq $activeHandle}            
$Process | Select ProcessName, @{Name="AppTitle";Expression= {($_.CloseMainWindow())}}            
} catch {            
 Write-Error "Failed to get active Window details. More Info: $_"            
}

```

Its a little slow but works. Also it won't close windows explorer. Need to look into it a little more.

**Comment by HikariKnight** [comment]
hey @Sokoloft i would just like to let you know i decided to include the "Close active window" functionality into hotkeyd, if it starts to interfere with anticheat i will rip the CloseWindow function out of the main project and instead make that a separate exe
